### ISSUE TITLE
Java低版本无法使用

### ISSUE THREAD

**Issue by 3328429240** [4o4E/EClean#21]
最新版启动的时候报错
[23:56:10] [Server thread/INFO]: [EClean] Enabling EClean v1.18.1
[23:56:10] [Server thread/ERROR]: 启用时发生错误 EClean v1.18.1 (Is it up to date?)
java.lang.UnsupportedClassVersionError: org/snakeyaml/engine/v2/exceptions/MarkedYamlEngineException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:?]
	at top.e404.eclean.relocate.kaml.Yaml.parseToYamlNode$kaml(Yaml.kt:72) ~[?:?]
	at top.e404.eclean.relocate.kaml.Yaml.decodeFromSource(Yaml.kt:62) ~[?:?]
	at top.e404.eclean.relocate.kaml.Yaml.decodeFromString(Yaml.kt:55) ~[?:?]
	at top.e404.eclean.relocate.eplugin.config.KtxConfig.load(KtxConfig.kt:73) ~[?:?]
	at top.e404.eclean.EClean.onEnable(EClean.kt:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:750) [?:?]
[23:56:10] [Server thread/INFO]: [EClean] Disabling EClean v1.18.1
[23:56:10] [Server thread/ERROR]: 禁用时发生错误EClean v1.18.1 (Is it up to date?)
top.e404.eclean.relocate.kotlin.UninitializedPropertyAccessException: lateinit property config has not been initialized
	at top.e404.eclean.relocate.eplugin.config.KtxConfig.getConfig(KtxConfig.kt:39) ~[?:?]
	at top.e404.eclean.EClean.getDebug(EClean.kt:46) ~[?:?]
	at top.e404.eclean.relocate.eplugin.menu.EMenuManager.shutdown(EMenuManager.kt:148) ~[?:?]
	at top.e404.eclean.EClean.onDisable(EClean.kt:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[%5b2%5dPaperSpigot-1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:750) [?:?]

应该是用的高版本Java构建导致的
希望推出Java8专版，谢谢作者！

**Comment by 4o4E** [comment]
等待

**Comment by LanQin996** [comment]
> 等待 [charleskorn/kaml#580](https://github.com/charleskorn/kaml/discussions/580)

您好是否已经修复我这边也是Java8目前无法使用

**Comment by 4o4E** [comment]
> > 等待 [charleskorn/kaml#580](https://github.com/charleskorn/kaml/discussions/580)
> 
> 您好是否已经修复我这边也是Java8目前无法使用

使用低版本

**Comment by 4o4E** [comment]
https://github.com/4o4E/EClean/releases/tag/1.19.0
