### ISSUE TITLE
1.16.1以上版本在paper1.8.8无法启动

### ISSUE THREAD

**Issue by 3328429240** [4o4E/EClean#22]
无法启动，报错如下
配置文件版本为1.16.1的
版本号大于1.16.1都无法启动，希望修复！
[05:09:09] [Server thread/INFO]: [EClean] Enabling EClean v1.17.2
[05:09:09] [Server thread/ERROR]: Error occurred while enabling EClean v1.17.2 (Is it up to date?)
top.e404.eclean.relocate.kaml.MissingRequiredPropertyException: Property 'trashcan' is required but it is missing.
	at top.e404.eclean.relocate.kaml.YamlInput.throwIfMissingRequiredPropertyException(YamlInput.kt:115) ~[?:?]
	at top.e404.eclean.relocate.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:106) ~[?:?]
	at top.e404.eclean.relocate.kaml.Yaml.decodeFromReader(Yaml.kt:54) ~[?:?]
	at top.e404.eclean.relocate.kaml.Yaml.decodeFromString(Yaml.kt:43) ~[?:?]
	at top.e404.eclean.relocate.eplugin.config.KtxConfig.load(KtxConfig.kt:72) ~[?:?]
	at top.e404.eclean.EClean.onEnable(EClean.kt:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]
Caused by: top.e404.eclean.relocate.kotlinx.serialization.MissingFieldException: Field 'trashcan' is required for type with serial name 'top.e404.eclean.config.ConfigData', but it was missing
	at top.e404.eclean.relocate.kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20) ~[?:?]
	at top.e404.eclean.config.ConfigData.<init>(Config.kt:32) ~[?:?]
	at top.e404.eclean.config.ConfigData$$serializer.deserialize(Config.kt:32) ~[?:?]
	at top.e404.eclean.config.ConfigData$$serializer.deserialize(Config.kt:32) ~[?:?]
	at top.e404.eclean.relocate.kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257) ~[?:?]
	at top.e404.eclean.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[?:?]
	at top.e404.eclean.relocate.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:104) ~[?:?]
	... 15 more
[05:09:09] [Server thread/INFO]: [EClean] Disabling EClean v1.17.2
[05:09:09] [Server thread/ERROR]: Error occurred while disabling EClean v1.17.2 (Is it up to date?)
top.e404.eclean.relocate.kotlin.UninitializedPropertyAccessException: lateinit property config has not been initialized
	at top.e404.eclean.relocate.eplugin.config.KtxConfig.getConfig(KtxConfig.kt:39) ~[?:?]
	at top.e404.eclean.EClean.getDebug(EClean.kt:46) ~[?:?]
	at top.e404.eclean.relocate.eplugin.menu.EMenuManager.shutdown(EMenuManager.kt:148) ~[?:?]
	at top.e404.eclean.EClean.onDisable(EClean.kt:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]

**Comment by 4o4E** [comment]
#21
