### ISSUE TITLE
使用 Mohist 服务端时，清理不成功

### ISSUE THREAD

**Issue by SuoHouDaiShi** [4o4E/EClean#31]
服务端：Mohist-1.20.1-863
服务器操作系统：Windows Server 2016 Standard
使用的 Java：OpenJDK 17
错误日志：
```
[18:54:25 INFO]: [EClean] 将在1分钟后进行清理
[18:54:25 INFO]: [EClean] 将在1分钟后进行清理
[18:54:55 INFO]: [EClean] 将在30秒后进行清理
[18:55:15 INFO]: [EClean] 将在10秒后进行清理
[18:55:25 INFO]: [EClean] 正在清理
[18:55:25 WARN]: [EClean] Task #21 for EClean v1.18.1 generated an exception
java.lang.IllegalStateException: cannot create item meta for AIR
        at top.e404.eclean.relocate.eplugin.util.ItemKt.editItemMeta(item.kt:41) ~[?:?]
        at top.e404.eclean.menu.trashcan.TrashInfo.generateItem(TrashInfo.kt:22) ~[?:?]
        at top.e404.eclean.menu.trashcan.TrashInfo.<init>(TrashInfo.kt:20) ~[?:?]
        at top.e404.eclean.clean.Trashcan.addItems(Trashcan.kt:90) ~[?:?]
        at top.e404.eclean.clean.DropKt.cleanDrop(drop.kt:125) ~[?:?]
        at top.e404.eclean.clean.DropKt.cleanDrop(drop.kt:42) ~[?:?]
        at top.e404.eclean.clean.Clean.clean(Clean.kt:54) ~[?:?]
        at top.e404.eclean.clean.Clean$schedule$2.invoke(Clean.kt:44) ~[?:?]
        at top.e404.eclean.clean.Clean$schedule$2.invoke(Clean.kt:31) ~[?:?]
        at top.e404.eclean.relocate.eplugin.EPlugin$InternalRunnable.run(EPlugin.kt:223) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:78) ~[forge-1.20.1-47.3.10-universal.jar%23349!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:416) ~[forge-1.20.1-47.3.10-universal.jar%23349!/:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1137) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:360) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1071) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:910) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23344!/:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by SuoHouDaiShi** [comment]
等会我眼瞎了，不支持 Mohist 且不能在这反馈问题，不好意思（
