### ISSUE TITLE
最新版在1.8.8paper出现报错无法使用

### ISSUE THREAD

**Issue by 3328429240** [4o4E/EClean#9]
### 出现报错，无法正常使用，不止这一个指令，希望系统性测试一下修复！
`
[12:54:19] [Server thread/INFO]: wangmeng123 issued server command: /ecl stats zy
[12:54:19] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ecl' in plugin EClean v1.15.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]
Caused by: java.lang.NoSuchMethodError: org/bukkit/Chunk.isForceLoaded()Z (loaded from file:/E:/春夏之梦云管理/server/server_core/Dream_Space7/cache/patched_1.8.8.jar by sun.misc.Launcher$AppClassLoader@cad73939) called from class top.e404.eclean.clean.CheckKt (loaded from file:/E:/春夏之梦云管理/server/server_core/Dream_Space7/plugins/%5B清理优化%5DEClean.jar by org.bukkit.plugin.java.PluginClassLoader@844f63b2).
	at top.e404.eclean.clean.CheckKt.sendWorldStats(Check.kt:39) ~[?:?]
	at top.e404.eclean.command.Stats.onCommand(Stats.kt:40) ~[?:?]
	at top.e404.eclean.relocate.eplugin.command.ECommandManager.onCommand(ECommandManager.kt:72) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
	... 15 more
`

**Comment by 4o4E** [comment]
fixed

https://github.com/4o4E/EClean/releases/tag/1.16.0
